// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4IocKzfraMCI97KuVVkhNqH_czsKB2eo',
    appId: '1:543293852495:web:140c979d3e67d56c41d33a',
    messagingSenderId: '543293852495',
    projectId: 'famunity-f604b',
    authDomain: 'famunity-f604b.firebaseapp.com',
    storageBucket: 'famunity-f604b.appspot.com',
    measurementId: 'G-4R6172JSLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtImFzlivEDG1GNXQ-22mF4tDRnUOGcc',
    appId: '1:543293852495:android:4ca44304e4dff43441d33a',
    messagingSenderId: '543293852495',
    projectId: 'famunity-f604b',
    storageBucket: 'famunity-f604b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOtMglzYo6Nc9IV1emepzUSrv0bHScnw',
    appId: '1:543293852495:ios:39c60da3babf1c6041d33a',
    messagingSenderId: '543293852495',
    projectId: 'famunity-f604b',
    storageBucket: 'famunity-f604b.appspot.com',
    iosBundleId: 'com.example.familyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOtMglzYo6Nc9IV1emepzUSrv0bHScnw',
    appId: '1:543293852495:ios:472670db44911ea941d33a',
    messagingSenderId: '543293852495',
    projectId: 'famunity-f604b',
    storageBucket: 'famunity-f604b.appspot.com',
    iosBundleId: 'com.example.familyManagement.RunnerTests',
  );
}
